### ISSUE TITLE
Use of EISCD files?

### ISSUE THREAD

**Issue by judgej** [cs278/bank-modulus#11]
I hope I haven't misunderstood how this works.

VocaLink provide regular EISCD files listing banks, sort codes, and the rules used to verify the bank accounts. I assume your hard-coded ranges in this package are derived from a subset of that data. Although it costs. for clients that have that file in some format (XML, CSV, SQL), is it possible to drive the validation rules from the supplied EISCD file or database instead?

I've not fully explored the EISCD files, but I'm assuming the algorithm used to validate sort+account numbers will depend on the sort code in the first instance.

Thanks.

**Comment by cs278** [comment]
I suggest you review the differences between modulus checking and EISCD. Modulus checks are a sanity check that user supplied bank details are correct (e.g. free of typos) without the accuracy and cost of EISCD.

https://www.vocalink.com/customer-support/modulus-checking/
https://www.vocalink.com/customer-support/eiscd/

Modulus checks are not infallible either `00-00-00 12345678` is considered valid whereas EISCD would tell you that's rubbish.

My company use modulus checking at point of entry and our payment system uses EISCD, the number of errors thrown up EISCD is negligible.

**Comment by judgej** [comment]
Thanks. That makes sense - there are a set of general validation rules for ranges of sort codes, and then there are list of specific sort codes that are actually in use.

Now, if I was in the business of creating bank account numbers for a sort code, would this library be the way to go here? I could chose random account numbers until hitting one that is valid and not yet used. Or create a table of possible account numbers to tick off as they are used. Or is there some kind of "reverse validation" function - out of scope here - that would map a number onto a valid account number (e.g. give me the 100^th valid account number)?
