### ISSUE TITLE
Ability to set "now"

### ISSUE THREAD

**Issue by judgej** [cs278/bank-modulus#21]
We have a use-case where we need to be able to run through historic transactions and validate them at the time they were created. To do that, we need to "wind time back" for this library to the time of the transaction. Would it be acceptable for this library to allow the current time that is used to choose the specification, to be set?

I realise there is a static method for setting up tests at specific times, but I was thinking more of a formal non-test method to change the time to any specified time.

Our use-case involves analysis of events leading up to an issue, so we can replay a series of events over a period.

Happy to submit a PR when we get to this stage, but just asking if this is something that would fit into your plans for this package first.

**Comment by cs278** [comment]
This wasn't a use case I'd considered but seems perfectly valid. I'll merge #25 next week and cut a new release.
