### ISSUE TITLE
Increased validation

### ISSUE THREAD

**Issue by apatkinson** [cs278/bank-modulus#33]
Does this code need to be added to the `SortCode` class `__construct`?

```PHP
if (strlen($value) > self::LENGTH && strpos($value, '-') === false) {
    throw SortCodeInvalidException::create($value);
}
```

**Comment by cs278** [comment]
https://github.com/cs278/bank-modulus/blob/161ca72b0cbb94b539189d27b513a5a6d4f7fef1/src/SortCode.php#L26-L28

Means you can only pass in **exactly** 6 digits.
